[build-system]
requires = ["setuptools", "wheel", "toml"]
build-backend = "setuptools.build_meta"

[project]
name = "vertex"
version = "0.0.1"
requires-python = ">=3.10,<3.11"

[tool.setuptools]
packages = ["vertex"]